config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    collection do
      get 'own'
      get 'search'
    end
  end

  resources :reservations do
    collection do
      get 'own'
      post 'confirm'
    end
  end

  get 'home/index'
  get 'home/show'

  get 'users/account'
  get 'users/profile'
  get 'users/profile/edit' => 'users#edit'

  root to: "rooms#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :checkin_date, presence: true
  validate :start_check
  validates :checkout_date, presence: true
  validate :start_end_check
  validates :count_people, presence: true

  private

  def start_check
    if Date.current > checkin_date
      errors.add(:checkin_date, "は過去の日付を登録できません")
    end
  end

  def start_end_check
    if checkin_date >= checkout_date
      errors.add(:checkout_date, "はチェックイン日より後の日付にしてください")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]

  # GET /reservations or /reservations.json
  def index
    @reservations = Reservation.all
  end

  def own
    @reservations = current_user.reservations
  end

  def confirm
    @reservation = Reservation.new(reservation_params)
    @room = Room.find(params[:reservation][:room_id])
    if @reservation.invalid?
      render "rooms/show"
    end
  end

  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    @room = Room.find(params[:reservation][:room_id])
    @reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
    render "rooms/show" and return if params[:back] || !@reservation.save
    redirect_to action: :own
  end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "Reservation was successfully updated." }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to action: :own, notice: "Reservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:checkin_date, :checkout_date, :count_people, :user_id, :room_id)
    end
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :checkin_date %>
    <%= form.date_select :checkin_date %>
  </div>

  <div class="field">
    <%= form.label :checkout_date %>
    <%= form.date_select :checkout_date %>
  </div>

  <div class="field">
    <%= form.label :count_people %>
    <%= form.number_field :count_people %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/confirm.html.erb
<div class="w-50 mx-auto card mt-3 px-3">
  <h2 class="text-center my-3">予約内容の確認</h2>
  <div class="d-flex justify-content-between">
    <h4>チェックイン</h4>
    <%= l @reservation.checkin_date %>
  </div>
  <div class="d-flex justify-content-between my-3">
    <h4>チェックアウト</h4>
    <%= l @reservation.checkout_date %>
  </div>
  <div class="d-flex justify-content-between">
    <h4>日数</h4>
    <p><%= (@reservation.checkout_date - @reservation.checkin_date).to_i %>日</p>
  </div>
  <div class="d-flex justify-content-between my-3">
    <h4>人数</h4>
    <p><%= @reservation.count_people %>人</p>
  </div>
  <div class="d-flex justify-content-between mb-3">
    <h4>合計金額</h4>
    <h4>¥<%= @reservation.room.price * (@reservation.checkout_date - @reservation.checkin_date).to_i %></h4>
  </div>
</div>

<%= form_with(model: @reservation) do |form| %>
  <%= form.hidden_field :checkin_date %>
  <%= form.hidden_field :checkout_date %>
  <%= form.hidden_field :count_people %>
  <%= form.hidden_field :room_id %>
  <div class="actions my-3 mx-auto w-50 text-center">
    <%= form.submit "予約する", class:"btn btn-primary" %>
    <%= form.submit "戻る", name: :back, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h2 class="my-3">再予約する</h2>

<div class="my-5">
  <%= link_to '←戻る', :back, class:"text-decoration-none h5" %>
</div>
<div class="d-flex">
  <%= image_tag @reservation.room.image, size: "500x300" %>
  <div class="card mx-5 w-100 px-3">
    <div class="d-flex justify-content-between mt-5">
      <h3><%= @reservation.room.name %></h3>
      <h3>¥<%= @reservation.room.price %>~</h3>
    </div>
    <h6><%= @reservation.room.address %></h6>
    <h5><%= @reservation.room.content %></h5>
    <%= form_with(model: @reservation) do |form| %>
      <% if @reservation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
          <ul>
            <% @reservation.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :checkin_date %>
        <%= form.date_select :checkin_date %>
      </div>

      <div class="field">
        <%= form.label :checkout_date %>
        <%= form.date_select :checkout_date %>
      </div>

      <div class="field">
        <%= form.label :count_people %>
        <%= form.number_field :count_people, min: 1 %>
      </div>

      <div class="actions my-3">
        <%= form.submit "再予約する", class:"btn btn-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Checkin date</th>
      <th>Checkout date</th>
      <th>Count people</th>
      <th>User</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.checkin_date %></td>
        <td><%= reservation.checkout_date %></td>
        <td><%= reservation.count_people %></td>
        <td><%= reservation.user_id %></td>
        <td><%= reservation.room_id %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/own.html.erb
<h2 class="my-3">予約済み一覧</h2>

<div class="table-responsive">
  <table class="table align-middle text-break">
    <thead>
      <tr>
        <th scope="col">画像</th>
        <th scope="col">施設名</th>
        <th scope="col" class="w-25">紹介文</th>
        <th scope="col">合計料金</th>
        <th scope="col">チェックイン</th>
        <th scope="col">チェックアウト</th>
        <th scope="col">予約確定日時</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |reservation| %>
        <tr>
          <td><%= image_tag reservation.room.image, size: '100x100' %></td>
          <td><%= reservation.room.name %></td>
          <td><%= reservation.room.content %></td>
          <td>¥<%= (reservation.count_people*reservation.room.price).to_s(:delimited) %></td>
          <td><%= l reservation.checkin_date %></td>
          <td><%= l reservation.checkout_date %></td>
          <td><%=  l reservation.updated_at %></td>
          <td><%= link_to '再予約', edit_reservation_path(reservation), class: "text-decoration-none" %></td>
          <td><%= link_to '取り消し', reservation, class: "text-decoration-none", method: :delete, data: { confirm: '本当に取り消しますか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reservations/show.html.erb
<p>
  <strong>Checkin date:</strong>
  <%= @reservation.checkin_date %>
</p>

<p>
  <strong>Checkout date:</strong>
  <%= @reservation.checkout_date %>
</p>

<p>
  <strong>Count people:</strong>
  <%= @reservation.count_people %>
</p>

<p>
  <strong>User:</strong>
  <%= @reservation.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @reservation.room_id %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>