config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    collection do
      get 'own'
      get 'search'
    end
  end

  resources :reservations do
    collection do
      get 'own'
      post 'confirm'
    end
  end

  get 'home/index'
  get 'home/show'

  get 'users/account'
  get 'users/profile'
  get 'users/profile/edit' => 'users#edit'

  root to: "rooms#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_one_attached :image
  has_many :reservations
  belongs_to :user

  before_create :default_image

  validates :name, presence: true
  validates :content, presence: true
  validates :price, presence: true
  validates :address, presence: true

  private

  def self.ransackable_attributes(auth_object = nil)
    ["address", "name", "content"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob", "reservations", "user"]
  end

  def default_image
    if !self.image.attached?
      self.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'room_defaultimage.jpeg')), filename: 'room_defaultimage.jpeg', content_type: 'image/jpeg')
    end
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :set_q, only: [:index, :search]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  def own
    @rooms = current_user.rooms
  end

  def search
    @results = @q.result
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @reservation = Reservation.new
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_q
      @q = Room.ransack(params[:q])
    end


    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name, :content, :price, :address, :image)
    end
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, class:"w-25 mx-auto mt-5") do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field my-1">
    <%= form.label :image, class: "form-label" %>
    <%= form.file_field :image, class: "form-control", type: "file" %>
  </div>

  <div class="field">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :content, class: "form-label" %>
    <%= form.text_area :content, class: "form-control", size:"20x5" %>
  </div>

  <div class="field">
    <%= form.label :price, class: "form-label" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :address, class: "form-label" %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="actions text-center my-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>

  <div class="text-center">
    <%= link_to '戻る', :back %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h4 class="text-center mt-5">編集</h4>

<%= render 'form', room: @room %>

app/views/rooms/index.html.erb
<%= search_form_for @q, url: search_rooms_path, class: "w-50 mx-auto my-5 py-5" do |f| %>
  <%= f.search_field :address_cont, placeholder:"エリア名を入力", class: "form-control" %>
  <br>
  <%= f.submit '検索', class:"btn btn-primary w-100" %>
<% end %>

<h1 class="text-center my-3">おすすめのエリア</h1>
<div class="row">
  <div class="col-3">
    <%= link_to image_tag("tokyo.jpeg", class:"img-fluid"), search_rooms_path(q: {address_cont: "東京" })%>
    <h3 class="text-center mt-2">東京</h3>
  </div>
  <div class="col-3">
    <%= link_to image_tag("osaka.jpeg", class:"img-fluid"), search_rooms_path(q: {address_cont: "大阪" })%>
    <h3 class="text-center mt-2">大阪</h3>
  </div>
  <div class="col-3">
    <%= link_to image_tag("kyoto.jpeg", class:"img-fluid"), search_rooms_path(q: {address_cont: "京都" })%>
    <h3 class="text-center mt-2">京都</h3>
  </div>
  <div class="col-3">
    <%= link_to image_tag("sapporo.jpeg", class:"img-fluid"), search_rooms_path(q: {address_cont: "札幌" })%>
    <h3 class="text-center mt-2">札幌</h3>
  </div>
</div>

app/views/rooms/new.html.erb
<h4 class="text-center mt-5">新規作成</h4>

<%= render 'form', room: @room %>

app/views/rooms/own.html.erb
<h2 class="my-3">登録済み一覧</h2>

<div class="table-responsive">
  <table class="table align-middle text-break">
    <thead>
      <tr>
        <th scope="col">画像</th>
        <th scope="col">施設名</th>
        <th scope="col" class="w-50">紹介文</th>
        <th scope="col">料金</th>
        <th scope="col">作成日</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr class>
          <td><%= image_tag room.image, size: '100x100' %></td>
          <td><%= link_to "#{room.name}", room, class: "text-decoration-none" %></td>
          <td><%= room.content %></td>
          <td>¥<%= room.price.to_s(:delimited) %>~</td>
          <td><%= l room.created_at, format: :short %></td>
          <td><%= link_to '編集', edit_room_path(room), class: "text-decoration-none" %></td>
          <td><%= link_to '削除', room, class: "text-decoration-none", method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/search.html.erb
<%= search_form_for @q, url: search_rooms_path, class: "d-flex w-50 mx-auto py-4" do |f| %>
  <%= f.search_field :address_cont, placeholder:"エリア名を入力", class: "form-control" %>
  <%= f.search_field :name_or_content_cont, placeholder:"キーワードを入力", class: "form-control mx-2" %>
  <%= f.submit '検索', class:"btn btn-primary" %>
<% end %>

<p class="my-2"><span class="h4"><%= @results.count %></span>件が見つかりました</p>

<div class="table-responsive">
  <table class="table align-middle text-break">
    <thead>
      <tr>
        <th scope="col" style="width:10%">画像</th>
        <th scope="col" style="width:10%">施設名</th>
        <th scope="col" style="width:20%">住所</th>
        <th scope="col" style="width:40%">紹介文</th>
        <th scope="col" style="width:20%">宿泊料金(/日)</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |room| %>
        <tr>
          <td><%= image_tag room.image, size: '100x100' %></td>
          <td><%= link_to "#{room.name}", room, class:"text-decoration-none" %></td>
          <td><%= room.address %></td>
          <td><%= room.content %></td>
          <td><%= room.price.to_s(:delimited) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/show.html.erb
<div class="my-5">
  <%= link_to '←戻る', :back, class:"text-decoration-none h5" %>
</div>
<div class="d-flex">
  <%= image_tag @room.image, size: "500x300" %>
  <div class="card mx-5 w-100 px-3">
    <div class="d-flex justify-content-between mt-5">
      <h3><%= @room.name %></h3>
      <h3>¥<%= @room.price %>~</h3>
    </div>
    <h6><%= @room.address %></h6>
    <h5><%= @room.content %></h5>
    <%= form_with(model: @reservation, url: confirm_reservations_path(@reservation)) do |form| %>
      <% if @reservation.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
          <ul>
            <% @reservation.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :checkin_date %>
        <%= form.date_select :checkin_date %>
      </div>

      <div class="field">
        <%= form.label :checkout_date %>
        <%= form.date_select :checkout_date %>
      </div>

      <div class="field">
        <%= form.label :count_people %>
        <%= form.number_field :count_people, min: 1 %>
      </div>
      <%= form.hidden_field :room_id, value: @room.id %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="actions my-3">
        <%= form.submit "確認画面へ", class:"btn btn-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>